apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
parameters:
    storagePolicyName: "vSAN Default Storage Policy"
    datastoreurl: "ds:///vmfs/volumes/vsan:ab63d8b67f154fae-af63786413302b82/"
